### Footstep parameterization for a large humanoid, similar to ASIMO or HRP-2 #

### footstep settings #########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float/double, integers will cause an exception
footsteps:
  x:      [0.30, 0.18, 0.30, 0.20, 0.30, 0.30, 0.20, 0.30, 0.30, 0.20, 0.30, 0.30, 0.20, 0.00,-0.18,-0.10, 0.00, 0.08, 0.18]
  y:      [0.30, 0.30, 0.25, 0.35, 0.30, 0.25, 0.35, 0.30, 0.25, 0.35, 0.30, 0.25, 0.35, 0.30, 0.30, 0.30, 0.33, 0.36, 0.31]
  theta:  [0.00, 0.00, 0.00, 0.00, 0.10, 0.10, 0.10, 0.20, 0.20, 0.20, 0.30, 0.30, 0.30, 0.00, 0.00, 0.40, 0.40, 0.20,-0.10]

#  x:      [0.30, 0.18, 0.10, 0.00, 0.00,-0.18, 0.00, 0.05, 0.10]
#  y:      [0.30, 0.30, 0.25, 0.41, 0.30, 0.30, 0.38, 0.4, 0.26]
#  theta:  [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.26, 0.26,-0.10]
  
#  x:      [0.42, 0.30, 0.18, 0.30, 0.30, 0.18, 0.00, 0.00,-0.18, 0.10, 0.18, 0.30, 0.30]
#  y:      [0.26, 0.26, 0.26, 0.21, 0.41, 0.46, 0.41, 0.26, 0.26, 0.42, 0.38, 0.36, 0.21]
#  theta:  [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.79, 0.52, 0.26,-0.10]

### foot settings #############################################################
foot:
  size: {x: 0.26, y: 0.16, z: 0.085}
  separation: 0.36
### sfeng: I think origin_shift := reference point on foot to the middle of the foot. 
### sfeng: for sf, the origin_shift is x = 0.045, idk about BDI
  origin_shift: {x: -0.045, y: 0.0}
  max:
    step: {x: 0.42, y: 0.42, theta: 0.6}
    inverse:
      step: {x: -0.18, y: 0.25, theta: -0.1}


### step range ################################################################

# more accurate than the bounding box defined by the max/max inverse step
step_range:
#  x: [0.32, 0.32,-0.12, 0.00]
#  y: [0.24, 0.20, 0.20, 0.38]
  x: [0.42, 0.30,-0.18, 0.30]
  y: [0.30, 0.25, 0.30, 0.40]

